In [8]:
import pandas as pd
import numpy as np

In [9]:
# Read the original 311 Dataset
data = pd.read_csv("../Data/311_Dataset.csv")
data.shape

(815417, 29)

In [10]:
# Sort the dataset by 'create_date_et' in descending order
data_sorted = data.sort_values(by='create_date_et', ascending=False)
data_sorted.head()

,_id,group_id,num_requests,parent_closed,status_name,status_code,dept,request_type_name,request_type_id,create_date_et,...,cross_street_id,city,neighborhood,census_tract,council_district,ward,police_zone,latitude,longitude,geo_accuracy
815416,815728,926123,1,f,open,0,Police - AVU,Abandoned Vehicle (parked on street),415,2025-03-10T10:28:00,...,NaN,Pittsburgh,Beechview,4.200319e+10,4.0,19.0,6.0,40.409814,-80.021726,APPROXIMATE
815415,815695,926118,1,f,open,0,Police - Zones 1-6,Illegal Parking,417,2025-03-04T12:17:00,...,NaN,Pittsburgh,East Liberty,4.200311e+10,9.0,8.0,5.0,40.460578,-79.927670,APPROXIMATE
815303,815578,926116,1,f,open,0,DPW - Street Maintenance,Port A Potty,4783,2025-02-04T14:04:00,...,0.0,Pittsburgh,Squirrel Hill South,NaN,5.0,14.0,4.0,40.435048,-79.947473,EXACT
815317,815592,926115,1,f,open,0,DPW - Street Maintenance,"Litter Can, Public",833,2025-02-04T13:59:00,...,0.0,Pittsburgh,Shadyside,NaN,8.0,7.0,4.0,40.457597,-79.919105,EXACT
815284,815559,926114,1,f,open,0,DPW - Street Maintenance,Potholes,484,2025-02-04T13:37:00,...,0.0,Pittsburgh,Squirrel Hill North,NaN,8.0,14.0,4.0,40.441242,-79.925190,EXACT

In [11]:
# Filter the dataset to include only the last 5 years of data
data_filtered = data[data['create_date_et'].str[:4].astype(int).isin([2025, 2024, 2023, 2022, 2021])]
data_filtered.head()

,_id,group_id,num_requests,parent_closed,status_name,status_code,dept,request_type_name,request_type_id,create_date_et,...,cross_street_id,city,neighborhood,census_tract,council_district,ward,police_zone,latitude,longitude,geo_accuracy
0,1,827262,1,f,open,0,DPW - Administration,Park Shelter,543,2024-03-12T10:50:00,...,NaN,Pittsburgh,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NULL_COORDINATES
1,2,720661,1,f,open,0,DPW - Administration,Park Shelter,543,2023-03-20T07:52:00,...,NaN,Pittsburgh,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NULL_COORDINATES
2,3,722010,1,f,open,0,DPW - Administration,Park Shelter,543,2023-03-24T07:44:00,...,NaN,Pittsburgh,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NULL_COORDINATES
3,4,846915,1,f,open,0,Police - Zones 1-6,Illegal Parking,417,2024-05-19T12:24:00,...,NaN,Pittsburgh,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NULL_COORDINATES
4,5,853708,1,f,open,0,DPW - Facilities,City Facility,375,2024-06-06T23:04:00,...,NaN,Pittsburgh,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NULL_COORDINATES

In [12]:
# Shape of the filtered dataset
data_filtered.shape

(387218, 29)

In [13]:
# Convert filtered data to a CSV file
data_filtered.to_csv("../Data/Filtered_311_Dataset.csv", index=False)