### Exploratory Data Analysis and Visualizations

In [19]:
import pandas as pd
import numpy as np
import seaborn as sns
%matplotlib inline 
import matplotlib.pyplot as plt
import plotly.express as px
import scipy.stats as stats

In [20]:
# Using a smaller dataset that focuses on the past five years (2021-2025) with dropped columns
# Load the dataset
data = pd.read_csv("../Data/CleanedData_311_Dataset.csv")
data.head()

,_id,group_id,num_requests,parent_closed,status_code,create_date_et,last_action_et,closed_date_et,council_district,ward,...,dept_simplified_Pittsburgh Water & Sewer Authority,dept_simplified_Pittsburgh Water and Sewer Authority,dept_simplified_Police,dept_simplified_Port Authority Transit,dept_simplified_Public Safety,dept_simplified_SPIN Scooters,dept_simplified_Sargent Electric,dept_simplified_School Guards,dept_simplified_Scoobi,dept_simplified_Urban Redevelopment Authority
0,97,626501,1,0,0,2022-04-24 09:56:00,2022-04-24 09:56:00,NaN,6.0,2.0,...,False,False,True,False,False,False,False,False,False,False
1,310,577909,1,0,3,2021-10-31 09:13:00,2021-11-30 09:21:00,NaN,7.0,11.0,...,False,False,False,False,False,False,False,False,False,False
2,376,620792,1,0,0,2022-04-01 07:33:00,2022-04-01 07:33:00,NaN,7.0,11.0,...,False,False,True,False,False,False,False,False,False,False
3,548,641351,1,0,0,2022-06-05 14:43:00,2022-06-05 14:43:00,NaN,7.0,11.0,...,False,False,True,False,False,False,False,False,False,False
4,793,569844,1,0,0,2021-09-30 11:42:00,2021-09-30 11:42:00,NaN,6.0,26.0,...,False,False,False,False,False,False,False,False,False,False

In [21]:
# Check the shape of the dataset
data.shape

(362859, 315)

In [22]:
# Sort the data by 'create_date_et' in descending order
data_sorted = data.sort_values(by='create_date_et', ascending=False)
# and display the first 5 rows
data_sorted.head()

,_id,group_id,num_requests,parent_closed,status_code,create_date_et,last_action_et,closed_date_et,council_district,ward,...,dept_simplified_Pittsburgh Water & Sewer Authority,dept_simplified_Pittsburgh Water and Sewer Authority,dept_simplified_Police,dept_simplified_Port Authority Transit,dept_simplified_Public Safety,dept_simplified_SPIN Scooters,dept_simplified_Sargent Electric,dept_simplified_School Guards,dept_simplified_Scoobi,dept_simplified_Urban Redevelopment Authority
362858,815728,926123,1,0,0,2025-03-10 10:28:00,2025-03-10 10:28:00,NaN,4.0,19.0,...,False,False,True,False,False,False,False,False,False,False
362857,815695,926118,1,0,0,2025-03-04 12:17:00,2025-03-04 12:17:00,NaN,9.0,8.0,...,False,False,True,False,False,False,False,False,False,False
362746,815578,926116,1,0,0,2025-02-04 14:04:00,2025-02-04 14:04:00,NaN,5.0,14.0,...,False,False,False,False,False,False,False,False,False,False
362759,815592,926115,1,0,0,2025-02-04 13:59:00,2025-02-04 13:59:00,NaN,8.0,7.0,...,False,False,False,False,False,False,False,False,False,False
362728,815559,926114,1,0,0,2025-02-04 13:37:00,2025-02-04 13:37:00,NaN,8.0,14.0,...,False,False,False,False,False,False,False,False,False,False

In [23]:
# Convert to datetime format
data_sorted['create_date_et'] = pd.to_datetime(data_sorted['create_date_et'])
data_sorted['last_action_et'] = pd.to_datetime(data_sorted['last_action_et'])
data_sorted['closed_date_et'] = pd.to_datetime(data_sorted['closed_date_et'])

In [24]:
# Collapse one-hot columns to single column values
data_sorted['status_name'] = data_sorted.filter(like='status_name_').idxmax(axis=1).str.replace('status_name_', '')
data_sorted['neighborhood'] = data_sorted.filter(like='neighborhood_').idxmax(axis=1).str.replace('neighborhood_', '')
data_sorted['category'] = data_sorted.filter(like='category_').idxmax(axis=1).str.replace('category_', '')
data_sorted['origin'] = data_sorted.filter(like='origin_').idxmax(axis=1).str.replace('origin_', '')
data_sorted['dept_simplified'] = data_sorted.filter(like='dept_simplified_').idxmax(axis=1).str.replace('dept_simplified_', '')

In [25]:
data_sorted.info()

<class 'pandas.core.frame.DataFrame'>
Index: 362859 entries, 362858 to 123971
Columns: 320 entries, _id to dept_simplified
dtypes: bool(294), datetime64[ns](3), float64(12), int64(6), object(5)
memory usage: 176.5+ MB

In [26]:
# Create dataframes for each status
df_closed = data_sorted[data_sorted['status_name'] == 'closed']
df_open = data_sorted[data_sorted['status_name'] == 'open']
df_in_progress = data_sorted[data_sorted['status_name'] == 'in progress']
df_on_hold = data_sorted[data_sorted['status_name'] == 'on hold']

In [27]:
# Visualize the distribution of 'origin'

# Distribution of Origin in All Requests
fig_all = px.bar(data_sorted['origin'].value_counts().reset_index(),
                 x='count', y='origin',
                 labels={'index': 'Origin', 'origin': 'Count'},
                 title='Distribution of Origin in All Requests',
                 color='origin')
fig_all.update_layout(xaxis=dict(tickangle=45))
fig_all.show()

# Distribution of Origin in Closed Requests
fig_closed = px.bar(df_closed['origin'].value_counts().reset_index(),
                    x='count', y='origin',
                    labels={'index': 'Origin', 'origin': 'Count'},
                    title='Distribution of Origin in Closed Requests',
                    color='origin',)
fig_closed.update_layout(xaxis=dict(tickangle=45))
fig_closed.show()

# Distribution of Origin in Open Requests
fig_open = px.bar(df_open['origin'].value_counts().reset_index(),
                  x='count', y='origin',
                  labels={'index': 'Origin', 'origin': 'Count'},
                  title='Distribution of Origin in Open Requests',
                  color='origin')
fig_open.update_layout(xaxis=dict(tickangle=45))
fig_open.show()

# Distribution of Origin in In Progress Requests
fig_in_progress = px.bar(df_in_progress['origin'].value_counts().reset_index(),
                         x='count', y='origin',
                         labels={'index': 'Origin', 'origin': 'Count'},
                         title='Distribution of Origin in In Progress Requests',
                         color='origin')
fig_in_progress.update_layout(xaxis=dict(tickangle=45))
fig_in_progress.show()

In [28]:
# Count the number of requests by status_name
status_counts = data_sorted['status_name'].value_counts()
print(status_counts)

status_name
closed         310623
open            30146
in progress     21713
on hold           377
Name: count, dtype: int64

In [ ]:
# Visualize the top 5 'category' 

# Function to create bar charts for top 5 categories
def plot_top_request_types(df, status_name):
    top_request_types = df['category'].value_counts().head(5).reset_index()
    fig = px.bar(
        top_request_types,
        x='category',
        y='count',
        labels={'index': 'Category Name', 'category': 'Count'},
        title=f'Top 5 Categories in {status_name.capitalize()} Requests',
        orientation='v',
        color='count',
        color_continuous_scale=px.colors.sequential.Sunset,
        text='count'
    )
    fig.update_layout()
    fig.show()

# Plot for Closed Requests
plot_top_request_types(df_closed, 'closed')

# Plot for Open Requests
plot_top_request_types(df_open, 'open')

# Plot for In Progress Requests
plot_top_request_types(df_in_progress, 'in progress')

In [30]:
# Visualize the top 5 Neighborhoods

# Function to create bar charts for top 5 neighborhoods
def plot_top_neighborhoods(df, status_name):
    top_neighborhoods = df['neighborhood'].value_counts().head(5).reset_index()
    fig = px.bar(
        top_neighborhoods,
        x='neighborhood',
        y='count',
        labels={'index': 'Neighborhood', 'neighborhood': 'Count'},
        title=f'Top 5 Neighborhoods in {status_name.capitalize()} Requests',
        orientation='v',
        color='count',
        color_continuous_scale=px.colors.sequential.Sunset,
        text='count'
    )
    fig.update_layout()
    fig.show()

# Plot for Closed Requests
plot_top_neighborhoods(df_closed, 'closed')
# Plot for Open Requests
plot_top_neighborhoods(df_open, 'open')
# Plot for In Progress Requests
plot_top_neighborhoods(df_in_progress, 'in progress')

In [31]:
# Create a new columns that contains the time taken to solve a case
data_sorted['time_taken'] = pd.to_datetime(data_sorted['closed_date_et']) - pd.to_datetime(data_sorted['create_date_et'])
# Convert the time taken to days
data_sorted['time_taken'] = data_sorted['time_taken'].dt.days

data_sorted['time_taken'].head()

362858   NaN
362857   NaN
362746   NaN
362759   NaN
362728   NaN
Name: time_taken, dtype: float64

In [32]:
# Analyse if there is a significant difference in time taken to solve cases across different departments
# Create a new DataFrame with only non-null values in 'dept' and 'time_taken'
data_sorted_clean = data_sorted.dropna(subset=['dept_simplified', 'time_taken']).copy()

# Example: Time taken vs Department
groups = [group['time_taken'].values for name, group in data_sorted_clean.groupby('dept_simplified')]
f_stat, p_val = stats.f_oneway(*groups)

print(f"F-statistic: {f_stat}, p-value: {p_val}")

F-statistic: 1199.7216719120504, p-value: 0.0

In [33]:
# Analyse if there is a significant difference in time taken to solve cases across different neighborhoods
# Create a new DataFrame with only non-null values in 'neighborhood' and 'time_taken'
data_sorted_clean = data_sorted.dropna(subset=['neighborhood', 'time_taken']).copy()

# Example: Time taken vs Neighborhood
groups = [group['time_taken'].values for name, group in data_sorted_clean.groupby('neighborhood')]
f_stat, p_val = stats.f_oneway(*groups)

print(f"F-statistic: {f_stat}, p-value: {p_val}")

F-statistic: 34.13288438766677, p-value: 0.0

In [34]:
# Analyse if there is a significant difference in time taken to solve cases across different service types
# Create a new DataFrame with only non-null values in 'category' and 'time_taken'
data_sorted_clean = data_sorted.dropna(subset=['category', 'time_taken']).copy()

# Example: Time taken vs Status Name
groups = [group['time_taken'].values for name, group in data_sorted_clean.groupby('category')]
f_stat, p_val = stats.f_oneway(*groups)

print(f"F-statistic: {f_stat}, p-value: {p_val}")

F-statistic: 366.6273147084651, p-value: 0.0